name: tests-orders

on:
  pull_request:
    paths:
      - 'complex/orders/**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd complex/orders && npm install && npm run test:ci
